//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalibrationWebApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstrumentInventory
    {
        public string InstrumentID { get; set; }
        public string PlantID { get; set; }
        public int SYSUserID { get; set; }
        public string InstrumentBrand { get; set; }
        public string InstrumentDesc { get; set; }
        public System.DateTime CalibrationDueDate { get; set; }
        public int RowCreatedSYSUserID { get; set; }
        public Nullable<System.DateTime> RowCReatedDateTime { get; set; }
        public int RowModifiedSYSUserID { get; set; }
        public Nullable<System.DateTime> RowModifiedDateTime { get; set; }
        public string Comments { get; set; }
    
        public virtual PlantsCollection PlantsCollection { get; set; }
        public virtual SYSUser SYSUser { get; set; }
    }
}
