//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalibrationWebApp.Models.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Tools_Registry_Entities : DbContext
    {
        public Tools_Registry_Entities()
            : base("name=Tools_Registry_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LOOKUPRole> LOOKUPRoles { get; set; }
        public virtual DbSet<SYSUser> SYSUsers { get; set; }
        public virtual DbSet<SYSUserRole> SYSUserRoles { get; set; }
        public virtual DbSet<PlantsCollection> PlantsCollections { get; set; }
        public virtual DbSet<EmployeeProfile> EmployeeProfiles { get; set; }
        public virtual DbSet<InstrumentInventory> InstrumentInventories { get; set; }
        public virtual DbSet<TOOL_CALIBRATION_VIEW> TOOL_CALIBRATION_VIEW { get; set; }

        public System.Data.Entity.DbSet<CalibrationWebApp.Models.ViewModel.UserSignUpView> UserSignUpViews { get; set; }
    }
}
